pylons:
  maximumRadius: 1000
  maxPylonHeight: 64
  minPylonHeight: 3
  targetXpPerLevelDay: 500
  pylonDepletion: 0.4
  samplesPerLevel: 2
  xpCollectionInterval: 30 # 30 seconds
  xpCalculationInterval: 600 # 10 minutes
  maxStoredXp: 4625 # 1 x Level 50
  xpPerBottle: 25
energy:
  seed: 256
  longRangeDistance: 10000
  midRangeDistance: 1000
  fieldChangeSeconds: 2592000 # 30 days
  maxTimesBackground: 4
materials:
  D: 57 # Diamond block
  I: 42 # Iron block
  L: 22 # Lapis block
  O: 49 # Obsidian
  interaction: 118 # Cauldron
items:
  divining: 345 # Compass
  activation: 345 # Compass
negativeEffects:
  cropGrowthReduction: 1.0 # Max chance to block
  cropGrowthBonusXp: 2.0
  treeGrowthReduction: 1.0
  treeGrowthBonusXp: 5.0
  fishReduction: 1.0
  naturalSpawnReduction: 1.0
  eggSpawnReduction: 0.7
  breedingReduction: 0.5
patterns:
  base: |
    **O**
    *OOO*
    OOOOO
    *OOO*
    **O**
  roof: |
    **O**
    *OOO*
    OODOO
    *OOO*
    **O**
  level: |
    **L**
    *ILI*
    LLDLL
    *ILI*
    **L**
data:
  saveInterval: 600
