pylons:
  maximumRadius: 1000
  maxPylonHeight: 64
  targetXpPerLevelDay: 500
  pylonDepletion: 0.4
materials:
  D: 57 # Diamond block
  I: 42 # Iron block
  L: 22 # Lapis block
  O: 49 # Obsidian
  interaction: 118 # Cauldron
items:
  divining: 345 # Compass
  activation: 345 # Compass
patterns:
  base: |
    **O**
    *OOO*
    OOOOO
    *OOO*
    **O**
  roof: |
    **O**
    *OOO*
    OODOO
    *OOO*
    **O**
  level: |
    **L**
    *ILI*
    LLDLL
    *ILI*
    **L**